apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-postgresql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitlab-postgresql
    spec:
      containers:
      - name: postgresql
        image: sameersbn/postgresql:9.5-3
        imagePullPolicy: Always
        env:
        - name: DB_USER
          value: $DB_USER
        - name: DB_PASS
          value: $DB_PASS
        - name: DB_NAME
          value: $DB_NAME
        - name: DB_EXTENSION
          value: $DB_EXTENSION
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresql-persistent-storage
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-persistent-storage
